### ISSUE TITLE
Documentation update required.

### ISSUE THREAD

**Issue by jainvikas8** [ARMmbed/mbed-os-example-crash-reporting#45]
Following instructions on https://github.com/ARMmbed/mbed-os-example-crash-reporting/commit/0b03d330b4b6326bae74e9ec3332bb1113e71649 doesn't result in working software.

After cloning and then following - https://github.com/ARMmbed/mbed-os-example-crash-reporting#building-and-running the `mbed compile -m ARM_MUSCA_A1_NS -t GCC_ARM` fails.

It's missing `mbed import` or `mbed deploy .` instructions.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTCORE-1604*

**Comment by adbridge** [comment]
@evedon  Who needs to look at this ?
