### ISSUE TITLE
Musca-A target does not work with this example

### ISSUE THREAD

**Issue by jainvikas8** [ARMmbed/mbed-os-example-crash-reporting#46]
On https://github.com/ARMmbed/mbed-os-example-crash-reporting/commit/0b03d330b4b6326bae74e9ec3332bb1113e71649 when using
`mbed compile -m ARM_MUSCA_A1_NS -t GCC_ARM` we don't get a desired output on the serial

---- Error ----
`[INF] Starting bootloader [ERR] Unable to find bootable image`

[ ] Question
[ ] Enhancement
[ x] Bug

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTCORE-1606*

**Comment by evedon** [comment]
This is an issue with your board, not the example.

**Comment by adbridge** [comment]
@evedon I have discussed this with @andypowers , whilst this board is not currently in our CI it is still mbed-enabled and thus should work with this example. This will not block the release but should stay open and the internal issue passed to the partner team (Marcelo etc)

**Comment by evedon** [comment]
The title is misleading and the issue should be opened in a different project.
The following program will fail as well:
```
int main()
{
    while (true) {
         sleep();
    }
}
```

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTCORE-1608*

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-2112*

**Comment by MarceloSalazar** [comment]
Note Musca_A is no longer supported in Mbed OS.
I suggest we close this issue.
