### ISSUE TITLE
Travis fails with `Error: No such command 'checkout'`

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-example-crash-reporting#66]
### Description of defect

The `mbed-tools` commands in `.travis.yml` are outdated, causing fails on PR checks.

#### Target(s) affected by this defect ?

Any

#### Toolchain(s) (name and version) displaying this defect ?

Any

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-6.9.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

mbed-tools 7.8.0

#### How is this defect reproduced ?

See Travis run: https://travis-ci.com/github/ARMmbed/mbed-os-example-crash-reporting/builds/222947619

**Comment by ciarmcom** [comment]
@LDong-Arm thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'. This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirrored to our internal defect tracking system or investigated until this has been fully resolved.

**Comment by Patater** [comment]
Merged https://github.com/ARMmbed/mbed-os-example-crash-reporting/pull/67
